spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tu_basededatos
    username: root
    password: taskmanager_db
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
